apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mtap-cluster
  region: us-east-1  
  version: "1.27"   

vpc:
  cidr: "172.31.0.0/16"  # Default CIDR; adjust if needed
  subnets:
    private:
      us-east-1a: { cidr: "192.168.1.0/24" }
      us-east-1b: { cidr: "192.168.2.0/24" }
    public:
      us-east-1a: { cidr: "192.168.3.0/24" }
      us-east-1b: { cidr: "192.168.4.0/24" }

nodeGroups:
  - name: mtap-drupal
    instanceType: t3.medium   # Choose an instance type
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    volumeSize: 20           # Storage size per node
    labels:
      role: drupal
    tags:
      Environment: dev
    ssh:
      allow: true
    privateNetworking: true   # Use private subnets for nodes

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AWSLoadBalancerControllerIAMPolicy
