apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mtap-cluster
  region: us-east-1  
  version: "1.27"   

vpc:
  id: "vpc-0382bcc1a39154f0a"  
  subnets:
    public:
      us-east-1a: { id: "subnet-02bec7f8f65198dca" }
      us-east-1b: { id: "subnet-0b5903c1c2240d8af" }


nodeGroups:
  - name: mtap-drupal
    instanceType: t3.medium   # Choose an instance type
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    volumeSize: 20           # Storage size per node
    labels:
      role: drupal
    tags:
      Environment: dev
    ssh:
      allow: true


cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AWSLoadBalancerControllerIAMPolicy
